// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGupPPjK3T-hBzkhpozFiJCxWc7ougXHU',
    appId: '1:108480222073:android:f264cc352f980aa58d95a8',
    messagingSenderId: '108480222073',
    projectId: 'ecommerce-4e22f',
    storageBucket: 'ecommerce-4e22f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_5mjnuAXaZqVAiqoF29xMOGIMI48xq0',
    appId: '1:108480222073:ios:f1298ac8182634838d95a8',
    messagingSenderId: '108480222073',
    projectId: 'ecommerce-4e22f',
    storageBucket: 'ecommerce-4e22f.firebasestorage.app',
    iosBundleId: 'com.josim.ecommerce.ecommerce',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrLu5cf7EVZP3CqY3r07X-7Oi-4naD9Eo',
    appId: '1:108480222073:web:885a97e8ad945ae58d95a8',
    messagingSenderId: '108480222073',
    projectId: 'ecommerce-4e22f',
    authDomain: 'ecommerce-4e22f.firebaseapp.com',
    storageBucket: 'ecommerce-4e22f.firebasestorage.app',
    measurementId: 'G-YK7HY8W413',
  );

}